### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by leandro-shifteight** [npm/lockfile#14]
I am getting this error and I have no idea what the problem is. Any idea on where to look at least?

.../tarifa/node_modules/cordova-lib/node_modules/npm/node_modules/lockfile/lockfile.js:46
      throw er
            ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by othiym23** [comment]
It sounds like something is running node with `--use_strict` or `--harmony` on the command line, which is probably not going to work, as the code base is way too massive to avoid strictness violations. Are you using any command line flags, and what version of node / io are you running?

**Comment by isaacs** [comment]
Yeah, this has to be something to do with a source code transmographier of some sort. Looks like either tarifa, cordova-lib, browserify, something, I dunno.
