### ISSUE TITLE
Avoiding writeFile collisions?

### ISSUE THREAD

**Issue by chovy** [npm/lockfile#20]
Is it possible with this module?

I have a lot of asynchronous tasks that all write JSON to the same file in parallel. I will often get a corrupted file because two functions write to the file at the same time.

Is there anyway to avoid this using `lockfile`?

**Comment by isaacs** [comment]
Yes! Create a lock file whose file name is deterministicly generated from the json file name. You may also like http://npm.in/write-file-atomic

**Comment by chovy** [comment]
Can you provide an example?
