### ISSUE TITLE
Catch exit by Ctrl+C

### ISSUE THREAD

**Issue by Redsandro** [npm/lockfile#21]
If the script is exited by Ctrl+C, the lock is not removed.

If the script exits normally, it is caught by [`process.on('exit')`](https://github.com/npm/lockfile/blob/master/lockfile.js#L33)

It should also listen to `process.on('SIGINT')` (linux at least).

**Comment by isaacs** [comment]
Indeed!  This module should probably use [signal-exit](http://npm.im/signal-exit) to remove locks.

**Comment by Redsandro** [comment]
Good catch, I hadn't seen that module before.
