### ISSUE TITLE
LOL not sure what just happened

### ISSUE THREAD

**Issue by ORESoftware** [npm/lockfile#22]
I had this file on my project filesystem called `server-pids.json`

I want to (1) lock the file, (2) read from it (3) write to it, (4) then unlock the file, seems like standard stuff

the problem is, this code just deleted the file from the filesystem, is that expected?

```js
  lockfile.lock(p, function (err) {                                // lock the file (?)
          fs.readFile(p, 'utf8', function (err, data) {
            if (err) {
              cb(err);
            }
            else {
              var pids;

              try {
                pids = JSON.parse(data);
                delete pids[pid];
              }
              catch (err) {
                console.log(err.stack || err);
                pids = {};
              }

              fs.writeFile(p, JSON.stringify(pids), function (err) {

                lockfile.unlock(p, function (err) {                               // unlock the file after writing (?)
                  if (err) {
                    console.log(err.stack || err);
                  }
                });
                if (err) {
                  console.log(' => fs.writeFile error => ', err.stack || err);
                  cb(err);
                }
                else {
                  cb(null);
                }
              });
            }

          });

        });
```

not sure what's up, but I laughed though

maybe if you delete files, it should be documented, or if it is then I didn't see it :)

**Comment by ORESoftware** [comment]
nevermind LOL I get it, you just pick a different file to lock to than the one you read/write from. Maybe add that as a simple use case in the docs.

**Comment by isaacs** [comment]
Yeah, lockfiles are not files that stick around.  Their existence implies that you have a lock on whatever they refer to.

Try doing `'path/to/my/apps/lockfiles/' + p.replace(/\\\//g, '-')` as the lock filename or something?

**Comment by ORESoftware** [comment]
yeah thx I just put the lock file in a different location altogether, nbd
