### ISSUE TITLE
Question: How to wait until file lock is removed

### ISSUE THREAD

**Issue by amilajack** [npm/lockfile#28]
Is there a recommended way of synchronously waiting until a file's lock has been removed?

**Comment by isaacs** [comment]
Nope.

If you use [slocket](http://npm.im/slocket), and async/await, you can do `await slocket(file)` to block on the promise resolving.

**Comment by isaacs** [comment]
Or if you want to give your fans a workout, you can do `while (true) { try { lockfile.lockSync(file) ; break } catch (er) {} }`.  But I wouldn't recommend it.
